apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: trigger-demo-el
  namespace: tekton-kids
  annotations:
    tekton.dev/payload-validation: "false"
spec:
  serviceAccountName: tekton-ci-listener
  triggers:
    - triggerRef: github-listener
  resources:
    kubernetesResource:
      serviceType: NodePort